"""
Handles generation and parsing of .inp input files.

The .inp format is an INI-style plain text file with [section] headers and key = value lines.
= signs are column-aligned within each section. Quantum label sections use a special format:
  label_name
  label_name = ffmt cfmt | description
"""
import json
import logging
import unicodedata
from datetime import date
from pathlib import Path

import config


# ---------------------------------------------------------------------------
# Standard label lookup
# ---------------------------------------------------------------------------

_standard_labels: dict[str, dict] | None = None


def _get_standard_labels() -> dict[str, dict]:
    """Returns a dict mapping label name → {Format quantum label, Description quantum label}."""
    global _standard_labels
    if _standard_labels is not None:
        return _standard_labels
    def _ascii(s: str) -> str:
        return unicodedata.normalize("NFKD", s).encode("ascii", errors="ignore").decode("ascii")

    try:
        path = config.standard_labels_path()
        with open(path, "r", encoding="utf-8") as f:
            raw: list[dict] = json.load(f)
        _standard_labels = {
            entry["Quantum label"]: {k: _ascii(v) if isinstance(v, str) else v for k, v in entry.items()}
            for entry in raw
        }
        logging.debug(f"inp_handler: loaded {len(_standard_labels)} standard labels")
    except Exception as e:
        logging.warning(f"inp_handler: could not load standard labels: {e}")
        _standard_labels = {}
    return _standard_labels


# ---------------------------------------------------------------------------
# .inp generation
# ---------------------------------------------------------------------------

def _align_section(pairs: list[tuple[str, str]]) -> list[str]:
    """Returns key = value lines with = signs aligned to the longest key."""
    if not pairs:
        return []
    max_key = max(len(k) for k, _ in pairs)
    lines = []
    for key, val in pairs:
        padding = max_key - len(key)
        lines.append(f"{key}{' ' * padding} = {val}")
    return lines


def _format_col_summary(summary: dict) -> str:
    """Formats a single column summary entry for the states preview comment block."""
    col = summary["col"]
    ctype = summary["type"]
    if ctype in ("integer", "float"):
        mn = summary["min"]
        mx = summary["max"]
        if ctype == "integer":
            return f"  col {col:>2}  {ctype:<8}  range  {int(mn)} - {int(mx)}"
        else:
            return f"  col {col:>2}  {ctype:<8}  range  {mn} - {mx}"
    else:
        vals = ", ".join(f"'{v}'" for v in summary["values"])
        if summary.get("more"):
            vals += ", ..."
        return f"  col {col:>2}  {ctype:<8}  values {vals}"


def _states_preview_block(iso_slug: str, states_summary: dict) -> list[str]:
    """Builds the commented states file preview block for the .inp file."""
    first_rows = states_summary.get("first_rows", [])
    columns = states_summary.get("columns", [])
    if not first_rows and not columns:
        return [f"# (States file summary not available for {iso_slug})"]

    lines = [f"# ---- States file preview ({iso_slug}) " + "-" * 40]
    if first_rows:
        lines.append("#  First 5 rows:")
        lines.append("#")
        for row in first_rows:
            lines.append("#    " + "  ".join(str(v) for v in row))
        lines.append("#")
    if columns:
        lines.append("#  Column summary (all rows):")
        for col_info in columns:
            lines.append("#" + _format_col_summary(col_info))
    lines.append("# " + "-" * 76)
    return lines


def generate_blank_inp(
    ds_name: str,
    iso_slugs: list[str],
    states_summaries: dict[str, dict],
    shared_quantum_labels: bool = False,
    extracted_data: dict[str, dict] | None = None,
) -> str:
    """
    Generates the blank .inp file content for a dataset.

    Parameters
    ----------
    ds_name : str
    iso_slugs : list of isotopologue slug names
    states_summaries : mapping of iso_slug → result of extractor.summarise_states_columns()
    shared_quantum_labels : if True, generates one [quantum_labels] section for all isotopologues
    extracted_data : mapping of iso_slug → result of extractor.extract_all() for the auto-info header
    """
    out = []
    today = date.today().isoformat()

    out += [
        "# " + "=" * 62,
        f"#  {ds_name}.inp  —  generated by def_creator --init  {today}",
        "#  Fill all blank values, then run: python create_def.py <work_dir>",
        "# " + "=" * 62,
        "",
    ]

    # [options]
    out += [
        "[options]",
        "# shared_quantum_labels  Set to true to use the same quantum labels for all isotopologues",
        "# ---- input " + "-" * 50,
    ]
    out += _align_section([
        ("shared_quantum_labels", "true" if shared_quantum_labels else "false"),
    ])
    out.append("")
    out.append("")

    # [dataset]
    out += [
        "# " + "=" * 62,
        "#  DATASET  (applies to all isotopologues)",
        "# " + "=" * 62,
        "[dataset]",
        "# doi                        Publication DOI",
        "# max_temperature            Maximum temperature of the linelist in K (author-stated, not the .pf max)",
        "# cooling_function_available true if a cooling function file is provided",
        "# specific_heat_available    true if a specific heat file is provided",
        "# continuum                  true if photo-absorption continuum cross-sections are included",
        "# ---- input " + "-" * 50,
    ]
    out += _align_section([
        ("doi",                        ""),
        ("max_temperature",            ""),
        ("cooling_function_available", "false"),
        ("specific_heat_available",    "false"),
        ("continuum",                  "false"),
    ])
    out.append("")
    out.append("")

    for iso_slug in iso_slugs:
        # Build auto-info header from extracted data
        auto_parts = []
        if extracted_data and iso_slug in extracted_data:
            d = extracted_data[iso_slug]
            iso = d.get("isotopologue", {})
            atoms = d.get("atoms", {})
            states = d.get("dataset", {}).get("states", {})
            trans = d.get("dataset", {}).get("transitions", {})
            pf = d.get("partition_function", {})

            auto_parts.append(
                f"iso_formula={iso.get('iso_formula', '?')}  "
                f"mass={iso.get('mass_in_Da', '?')} Da  "
                f"atoms={atoms.get('number_of_atoms', '?')}"
            )
            auto_parts.append(
                f"states={states.get('number_of_states', '?')}  "
                f"transitions={trans.get('number_of_transitions', '?')}  "
                f"max_energy={states.get('max_energy', '?')} cm-1"
            )
            auto_parts.append(
                f"pf_max_temp={pf.get('max_partition_function_temperature', '?')} K  "
                f"pf_step={pf.get('partition_function_step_size', '?')} K"
            )

        out += ["# " + "=" * 62, f"#  ISOTOPOLOGUE: {iso_slug}"]
        for part in auto_parts:
            out.append(f"#  Auto-derived: {part}")
        out.append("# " + "=" * 62)
        out.append("")

        # States preview
        summary = states_summaries.get(iso_slug, {})
        out += _states_preview_block(iso_slug, summary)
        out.append("")

        # [isotopologue.slug]
        out += [
            f"[isotopologue.{iso_slug}]",
            "# inchi               InChI identifier for the isotopologue (e.g. InChI=1S/Al.H/i2*1+0)",
            "# inchikey            InChIKey for the isotopologue (e.g. SPRIOUNJHPCKPV-MHGBRSHDSA-N)",
            "# cas_registry_number CAS registry number (leave blank if not applicable)",
            "# point_group         Symmetry group (e.g. C, Cs, C2v, Dinfh, ...)",
            "# irreps              Irreducible representations as label:degeneracy pairs (e.g. Sigma+:12, Sigma-:12)",
            "# quantum_case_label  Quantum coupling case label (e.g. dos, dcs, hunda, hundb, lpcs, ...)",
            "# ---- input " + "-" * 50,
        ]
        out += _align_section([
            ("inchi",               ""),
            ("inchikey",            ""),
            ("cas_registry_number", ""),
            ("point_group",         ""),
            ("irreps",              ""),
            ("quantum_case_label",  ""),
        ])
        out.append("")

        # [quantum_labels]
        if not shared_quantum_labels or iso_slug == iso_slugs[0]:
            section = "[quantum_labels]" if shared_quantum_labels else f"[quantum_labels.{iso_slug}]"
            out += [
                section,
                "# One label per line: name  or  name = ffmt cfmt | description",
                "# Labels in the standard library auto-fill format and description.",
                "# First 4 are standard header columns: change J to F for hyperfine datasets,",
                "#   or J to N for symmetric tops (no extra flags set for N).",
                "# Auxiliary columns use prefix 'Auxiliary:' and go at the end.",
                "#",
                "# Auto-detected from label names:",
                "#   4th column = F  → hyperfine_resolved      = true",
                "#   unc            → uncertainties_available  = true",
                "#   tau            → lifetime_available       = true",
                "#   gfactor        → lande_g_available        = true",
                "#   unique namespaces (e.g. hunda:) count toward num_quantum_types",
                "#",
                "# ---- input " + "-" * 50,
                "ID",
                "E",
                "gtot",
                "J",
            ]
            out.append("")
            out.append("")

    return "\n".join(out)


def write_inp(content: str, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    logging.info(f"inp_handler: wrote '{path}'")


# ---------------------------------------------------------------------------
# .inp parsing
# ---------------------------------------------------------------------------

_BOOL_MAP = {
    "true": True, "yes": True, "1": True,
    "false": False, "no": False, "0": False,
}

_NON_QUANTA_LABELS = {"unc", "tau", "gfactor"}  # boolean-flag columns, not quantum numbers
_HEADER_COUNT = 4  # ID, E, gtot, and the 4th column (J / F / N)

# Fallback formats for the 4 standard header columns and common 4th-column variants
_HEADER_DEFAULTS: dict[str, dict] = {
    "ID":   {"ffmt": "I12",   "cfmt": "%12d",   "desc": "Unique integer identifier for the energy level"},
    "E":    {"ffmt": "F12.6", "cfmt": "%12.6f", "desc": "State energy in cm-1"},
    "gtot": {"ffmt": "I6",    "cfmt": "%6d",    "desc": "Total energy level degeneracy"},
    "J":    {"ffmt": "I7",    "cfmt": "%7d",    "desc": "Total rotational quantum number, excluding nuclear spin"},
    "F":    {"ffmt": "F7.1",  "cfmt": "%7.1f",  "desc": "Total angular momentum quantum number, including nuclear spin"},
    "N":    {"ffmt": "I7",    "cfmt": "%7d",    "desc": "Rotational quantum number"},
}


def _parse_bool(val: str, key: str) -> bool:
    v = val.strip().lower()
    if v not in _BOOL_MAP:
        raise ValueError(f"Invalid boolean value '{val}' for key '{key}'")
    return _BOOL_MAP[v]


def _parse_irreps(val: str) -> dict[str, int]:
    """Parses 'Sigma+:12, Sigma-:12' → {'Sigma+': 12, 'Sigma-': 12}."""
    result = {}
    for part in val.split(","):
        part = part.strip()
        if not part:
            continue
        if ":" not in part:
            raise ValueError(f"Cannot parse irrep '{part}' — expected 'label:degeneracy'")
        label, deg = part.rsplit(":", 1)
        result[label.strip()] = int(deg.strip())
    return result


def _parse_quantum_label_line(line: str, standard_labels: dict) -> dict | None:
    """
    Parses one quantum label line from a [quantum_labels.*] section.
    Returns a states_file_fields dict or None if the line is empty/comment.
    Format: name  or  name = ffmt cfmt | description
    """
    line = line.strip()
    if not line or line.startswith("#"):
        return None

    if "=" in line:
        name, rest = line.split("=", 1)
        name = name.strip()
        rest = rest.strip()
        if "|" in rest:
            fmt_part, desc = rest.split("|", 1)
            fmt_tokens = fmt_part.strip().split()
            ffmt = fmt_tokens[0] if len(fmt_tokens) > 0 else ""
            cfmt = fmt_tokens[1] if len(fmt_tokens) > 1 else ""
            desc = desc.strip()
        else:
            fmt_tokens = rest.strip().split()
            ffmt = fmt_tokens[0] if len(fmt_tokens) > 0 else ""
            cfmt = fmt_tokens[1] if len(fmt_tokens) > 1 else ""
            desc = ""
    else:
        name = line
        ffmt = cfmt = desc = ""

    # Auto-fill from standard labels if not provided
    if not ffmt or not desc:
        bare = name.split(":", 1)[1].strip() if ":" in name else name
        std = standard_labels.get(name) or standard_labels.get(bare)
        if std:
            fmt_str = std.get("Format quantum label", "")
            if fmt_str and not ffmt:
                parts = fmt_str.split()
                ffmt = parts[0] if parts else ""
                cfmt = parts[1] if len(parts) > 1 else ""
            if not desc:
                desc = std.get("Description quantum label", "")

    # Fallback defaults for standard header columns (ID, E, gtot, J, F, N)
    if not ffmt or not desc:
        hdr = _HEADER_DEFAULTS.get(name)
        if hdr:
            if not ffmt:
                ffmt, cfmt = hdr["ffmt"], hdr["cfmt"]
            if not desc:
                desc = hdr["desc"]

    return {"name": name, "ffmt": ffmt, "cfmt": cfmt, "desc": desc}


def _auto_detect_flags(labels: list[dict]) -> dict:
    """
    Derives boolean availability flags and num_quantum_types from the full label list,
    which includes the 4 standard header columns at positions 0–3.
    Hyperfine is detected from the 4th label (index 3) being 'F'.
    """
    names = [lbl["name"] for lbl in labels]

    # Hyperfine: 4th column specifically named F
    fourth = names[_HEADER_COUNT - 1] if len(names) >= _HEADER_COUNT else ""
    hyperfine = (fourth == "F")

    # Flags and counts from non-header labels only
    non_header = names[_HEADER_COUNT:]
    uncertainties = "unc" in non_header
    lifetime = "tau" in non_header
    lande_g = "gfactor" in non_header

    namespaces: set[str] = set()
    for name in non_header:
        if ":" in name:
            ns, _ = name.split(":", 1)
            ns = ns.strip()
            if ns and ns.lower() != "auxiliary":
                namespaces.add(ns)

    non_aux = [n for n in non_header if not n.startswith("Auxiliary:") and n not in _NON_QUANTA_LABELS]
    num_quanta = len(non_aux)

    return {
        "uncertainties_available": uncertainties,
        "lifetime_available": lifetime,
        "lande_g_available": lande_g,
        "hyperfine_resolved_dataset": hyperfine,
        "num_quantum_types": len(namespaces),
        "num_quanta": num_quanta,
    }



def parse_inp(inp_path: Path) -> dict:
    """
    Parses a filled .inp file and returns a nested dict in exomol.json key structure,
    populated with user-supplied values. Auto-derives boolean flags from quantum labels.

    Returns a dict with top-level keys: 'dataset', 'per_isotopologue', 'options'.
    'per_isotopologue' maps iso_slug → dict of user-supplied isotopologue fields.
    """
    logging.info(f"inp_handler: parsing '{inp_path}'")
    standard_labels = _get_standard_labels()

    # Read and segment file into sections
    sections: dict[str, list[str]] = {}
    current_section: str | None = None

    with open(inp_path, "r", encoding="utf-8") as f:
        for raw_line in f:
            line = raw_line.rstrip("\n")
            stripped = line.strip()
            if stripped.startswith("[") and stripped.endswith("]"):
                current_section = stripped[1:-1]
                sections.setdefault(current_section, [])
            elif current_section is not None:
                sections[current_section].append(line)

    def _kv_pairs(section_lines: list[str]) -> dict[str, str]:
        """Parse key = value lines (ignoring comments and blanks)."""
        result = {}
        for line in section_lines:
            stripped = line.strip()
            if not stripped or stripped.startswith("#"):
                continue
            if "=" in stripped:
                key, _, val = stripped.partition("=")
                result[key.strip()] = val.strip()
        return result

    # Parse [options]
    options_kv = _kv_pairs(sections.get("options", []))
    shared_qn = _parse_bool(options_kv.get("shared_quantum_labels", "false"), "shared_quantum_labels")

    # Parse [dataset]
    dataset_kv = _kv_pairs(sections.get("dataset", []))
    dataset_out: dict = {}
    if "doi" in dataset_kv:
        dataset_out["doi"] = dataset_kv["doi"] or None
    if "max_temperature" in dataset_kv and dataset_kv["max_temperature"]:
        dataset_out["max_temperature"] = float(dataset_kv["max_temperature"])
    bool_flags = ("cooling_function_available", "specific_heat_available", "continuum")
    for flag in bool_flags:
        if flag in dataset_kv and dataset_kv[flag]:
            dataset_out[flag] = _parse_bool(dataset_kv[flag], flag)

    # Parse shared quantum labels (if present)
    shared_labels: list[dict] | None = None
    if shared_qn and "quantum_labels" in sections:
        raw_labels = []
        for line in sections["quantum_labels"]:
            parsed = _parse_quantum_label_line(line, standard_labels)
            if parsed:
                raw_labels.append(parsed)
        if raw_labels:
            shared_labels = raw_labels

    # Collect all isotopologue sections
    iso_sections = {
        k: v for k, v in sections.items()
        if k.startswith("isotopologue.")
    }

    per_isotopologue: dict[str, dict] = {}
    for section_name, section_lines in iso_sections.items():
        iso_slug = section_name[len("isotopologue."):]
        kv = _kv_pairs(section_lines)
        iso_out: dict = {}

        if "inchi" in kv and kv["inchi"].strip():
            iso_out["inchi"] = kv["inchi"].strip()
        if "inchikey" in kv and kv["inchikey"].strip():
            iso_out["inchikey"] = kv["inchikey"].strip()
        if "cas_registry_number" in kv and kv["cas_registry_number"].strip():
            iso_out["cas_registry_number"] = kv["cas_registry_number"].strip()
        if "point_group" in kv and kv["point_group"]:
            iso_out["point_group"] = kv["point_group"].strip()
        if "irreps" in kv and kv["irreps"]:
            iso_out["irreducible_representations"] = _parse_irreps(kv["irreps"])
        if "quantum_case_label" in kv and kv["quantum_case_label"]:
            iso_out["quantum_case_label"] = kv["quantum_case_label"].strip()

        # Parse quantum labels
        if shared_qn and shared_labels is not None:
            raw_labels = shared_labels
        else:
            qn_section_key = f"quantum_labels.{iso_slug}"
            raw_labels = []
            if qn_section_key in sections:
                for line in sections[qn_section_key]:
                    parsed = _parse_quantum_label_line(line, standard_labels)
                    if parsed:
                        raw_labels.append(parsed)

        if raw_labels:
            flags = _auto_detect_flags(raw_labels)
            iso_out.update(flags)
            iso_out["states_file_fields"] = raw_labels
            logging.debug(
                f"inp_handler: '{iso_slug}' — {len(raw_labels)} user labels, "
                f"num_quantum_types={flags['num_quantum_types']}, "
                f"num_quanta={flags['num_quanta']}"
            )

        per_isotopologue[iso_slug] = iso_out

    result = {
        "options": {"shared_quantum_labels": shared_qn},
        "dataset": dataset_out,
        "per_isotopologue": per_isotopologue,
    }
    logging.info(
        f"inp_handler: parsed {len(per_isotopologue)} isotopologue(s): "
        f"{list(per_isotopologue)}"
    )
    return result
